### PR TITLE
PR: Use auth_plug to simplify auth in MPV App issue #65

### PR DESCRIPTION
**Pull request by nelsonic**
This Pull Request:

+ [x] Migrates the MVP to use `auth_plug` to _eliminate_ all auth-related code from the project. ✂️ 
+ [x] Adds additional tests to get the project up to 100% test coverage 💯 
+ [x] Ensure that _existing_ functionality is working ... 

By adding `auth_plug` to `mix.exs` and 4 lines of code to the `router.ex` file we can completely eliminate 
the rest of the auth-related code in the project and just focus on building the _features_ we _actually_ want
and never _think_ about how `auth` works unless we need to add a specific new feature.

### CODE REVIEW

**Comment by nelsonic** [comment]
Minor detour: https://github.com/dwyl/auth/issues/130 ... ⏳

**Comment by nelsonic** [comment]
Updated Auth: https://github.com/dwyl/auth/pull/131 ✅ 
Back to this PR. 👨‍💻

**Comment by nelsonic** [comment]
@iteles this PR is reviewable. Please let me know if you have any questions. Thanks. ☀️

**Review by iteles — APPROVED** [review]
@nelsonic Thank you! LGTM. 
Don’t want to delay #67 further either, merging this in 👍🏻

**Pull request merged**
