### PR TITLE
PR: Rename Kinds to Tags for Simplicity 

### PR DESCRIPTION
**Pull request by nelsonic**
+ [x] reduce size of MVP loop diagram in `README.md` https://github.com/dwyl/app-mvp-phoenix/issues/1
+ [x] Add "***Who?***" section to  `README.md` to clarify target audience. 
+ [x] Rename **`kinds`** to **`tags`** as discussed in https://github.com/dwyl/app/issues/232
+ [x] Create **`item_tags`** lookup table
+ [x] Update all ERDs to reflect latest data structure
app-er-diagram-with-item_tags

### CODE REVIEW

**Comment by nelsonic** [comment]
Failing test due to adding a `belongs_to :list, App.Ctx.List` constraint to `items` ... 🙄 
image

The failures are basically all the same. Fixing them won't take too long ... 📝 
```
  1) test items delete_item/1 deletes the item (App.CtxTest)
     test/app/ctx_test.exs:244
     Expected exception Ecto.NoResultsError but got Postgrex.Error (ERROR 42703 (undefined_column) column i0.list_id does not exist

         query: SELECT i0."id", i0."text", i0."person_id", i0."status", i0."list_id", i0."inserted_at", i0."updated_at" FROM "items" AS i0 WHERE (i0."id" = $1))
     code: assert_raise Ecto.NoResultsError, fn -> Ctx.get_item!(item.id) end
     stacktrace:
       (ecto_sql) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1
       (ecto_sql) lib/ecto/adapters/sql.ex:562: Ecto.Adapters.SQL.execute/5
       (ecto) lib/ecto/repo/queryable.ex:177: Ecto.Repo.Queryable.execute/4
       (ecto) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
       (ecto) lib/ecto/repo/queryable.ex:105: Ecto.Repo.Queryable.one!/3
       test/app/ctx_test.exs:247: (test)
```

**Comment by nelsonic** [comment]
@SimonLab if you have time to remote-pair on this, I'm sure it's very easy to fix, but I'm not seeing it.

**Comment by SimonLab** [comment]
I'm going to try on my localhost. The error is that the `list_id` is not defined when getting elements form Postgres.
I'll check
- [ ] if `list_id` is required/define and if we need it?
- [ ] if the foreign key is properly set for the `list`?
- [ ] if it should just be `id`?

**Comment by nelsonic** [comment]
@SimonLab yeah, it's just that we need to define a **`list`** when creating an **`item`**.
I'm on the Zoom (standup) call if you have time to remote pair on debugging this.

**Comment by SimonLab** [comment]
I just pull this branch and run `mix ecto.migrate` and add the following error:
image

I'm not sure if I should have deleted completely my database first or if there is an error with the status migration.
I'll try first to reset the database and run the migration again ( I need to remember what is the mix command for this)

**Comment by nelsonic** [comment]
@SimonLab you will need to `mix ecto.drop && mix ecto.create && mix ecto.create` for it to work.
(_because you already have an `app_dev` database ..._)

**Comment by nelsonic** [comment]
Stupid git gave me a merge conflict on my own branch ... 🙄 
https://travis-ci.com/dwyl/app-mvp-phoenix/builds/136415411#L338

**Comment by nelsonic** [comment]
@SimonLab I believe this PR is in a reviewable state.
Sorry for all the changes, "Kinds" >> "Tags" are all over the codebase 
so it was _easier_ to re-do the whole migrations folder ...

Please let me know your feedback.
If it's OK to merge, please merge.
Thanks!

**Comment by nelsonic** [comment]
Thanks @SimonLab ☀️

**Pull request merged**
